--------------------------------------------------------
--  DDL for Table TBL_ATTACH
--------------------------------------------------------

  CREATE TABLE "BOOK_EX"."TBL_ATTACH" 
   (	"UUID" VARCHAR2(100 BYTE), 
	"UPLOADPATH" VARCHAR2(200 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILETYPE" CHAR(1 BYTE) DEFAULT 'I', 
	"BNO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
